INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (1, '骨科', '宗芸', '18060100208', '1');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (2, '烧伤科', '黄浩勇', '17010760014', '2');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (3, '皮肤科', '钟芯茹', '18060300106', '3');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (4, '精神科', '朱晶晶', '18050300233', '4');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (5, '儿科', '李梦珂', '18030606017', '5');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (6, '内科', '方嘉瑶', '18050300127', '6');
INSERT INTO hospital.myapp_dept (id, dept_name, dept_manager, dept_manager_telep, dept_floor) VALUES (7, '外科', '陈雨菲', '18060100218', '7');
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (1, '1001', '高特', '男', '30', '18010600104', '主任医师', 1);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (2, '1002', '周阳阳', '男', '31', '18010300222', '主任医师', 2);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (3, '1003', '李慧贤', '女', '35', '18010300219', '主任医师', 2);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (4, '1004', '郑武', '男', '40', '18010100322', '主任医师', 3);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (5, '1005', '尹可欣', '女', '42', '18010100222', '主任医师', 1);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (6, '1006', '赖奋发', '男', '38', '17060300133', '主任医师', 7);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (7, '1007', '袁键鑫', '男', '36', '17050800269', '主任医师', 4);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (8, '1008', '钟林林', '女', '29', '17050200320', '主任医师', 6);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (9, '1009', '杨敬锴', '男', '31', '17040600106', '主任医师', 2);
INSERT INTO hospital.myapp_doctor (id, doctor_id, doctor_name, doctor_sex, doctor_age, doctor_telep, doctor_position, doctor_dept_id) VALUES (10, '1010', '郭涛', '男', '35', '17030300619', '主任医师', 4);
INSERT INTO hospital.myapp_medicine (id, medicine_name, medicine_num) VALUES (1, '红霉素', 300);
INSERT INTO hospital.myapp_medicine (id, medicine_name, medicine_num) VALUES (2, '云南白药', 500);
INSERT INTO hospital.myapp_medicine (id, medicine_name, medicine_num) VALUES (3, '皮炎平', 300);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (1, '1', '空', '空', 1);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (2, '2', '空', '空', 1);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (3, '3', '空', '空', 1);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (4, '4', '空', '空', 1);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (5, '5', '空', '空', 1);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (6, '1', '空', '空', 2);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (7, '2', '空', '空', 2);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (8, '3', '空', '空', 2);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (9, '4', '空', '空', 2);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (10, '5', '空', '空', 2);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (11, '1', '空', '空', 3);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (12, '2', '空', '空', 3);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (13, '3', '空', '空', 3);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (14, '4', '空', '空', 3);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (15, '5', '空', '空', 3);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (16, '1', '空', '空', 4);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (17, '2', '空', '空', 4);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (18, '3', '空', '空', 4);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (19, '4', '空', '空', 4);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (20, '5', '空', '空', 4);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (21, '1', '空', '空', 5);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (22, '2', '空', '空', 5);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (23, '3', '空', '空', 5);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (24, '4', '空', '空', 5);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (25, '5', '空', '空', 5);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (26, '1', '空', '空', 6);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (27, '2', '空', '空', 6);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (28, '3', '空', '空', 6);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (29, '4', '空', '空', 6);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (30, '5', '空', '空', 6);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (31, '1', '空', '空', 7);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (32, '2', '空', '空', 7);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (33, '3', '空', '空', 7);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (34, '4', '空', '空', 7);
INSERT INTO hospital.myapp_room (id, room_id, room_patient_id, room_patient_name, room_patient_dept_id) VALUES (35, '5', '空', '空', 7);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (3, '高特', '周一', 1, 1);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (4, '高特', '周三', 1, 1);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (5, '高特', '周五', 1, 1);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (6, '尹可欣', '周二', 1, 5);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (7, '尹可欣', '周四', 1, 5);
INSERT INTO hospital.myapp_work (id, work_doctor_name, work_time, work_doctor_dept_id, work_doctor_id_id) VALUES (8, '尹可欣', '周六', 1, 5);